/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { PUMP_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const SELL_TOKEN_DISCRIMINATOR = new Uint8Array([
  109, 61, 40, 187, 230, 176, 135, 174,
]);

export function getSellTokenDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(SELL_TOKEN_DISCRIMINATOR);
}

export type SellTokenInstruction<
  TProgram extends string = typeof PUMP_PROGRAM_ADDRESS,
  TAccountSigner extends string | IAccountMeta<string> = string,
  TAccountTokenAta extends string | IAccountMeta<string> = string,
  TAccountSolEscrow extends string | IAccountMeta<string> = string,
  TAccountTokenEscrow extends string | IAccountMeta<string> = string,
  TAccountBondingCurve extends string | IAccountMeta<string> = string,
  TAccountTokenMint extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountAssociatedTokenProgram extends
    | string
    | IAccountMeta<string> = 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            IAccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountTokenAta extends string
        ? WritableAccount<TAccountTokenAta>
        : TAccountTokenAta,
      TAccountSolEscrow extends string
        ? WritableAccount<TAccountSolEscrow>
        : TAccountSolEscrow,
      TAccountTokenEscrow extends string
        ? WritableAccount<TAccountTokenEscrow>
        : TAccountTokenEscrow,
      TAccountBondingCurve extends string
        ? WritableAccount<TAccountBondingCurve>
        : TAccountBondingCurve,
      TAccountTokenMint extends string
        ? ReadonlyAccount<TAccountTokenMint>
        : TAccountTokenMint,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type SellTokenInstructionData = {
  discriminator: ReadonlyUint8Array;
  maxToken: bigint;
};

export type SellTokenInstructionDataArgs = { maxToken: number | bigint };

export function getSellTokenInstructionDataEncoder(): Encoder<SellTokenInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['maxToken', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SELL_TOKEN_DISCRIMINATOR })
  );
}

export function getSellTokenInstructionDataDecoder(): Decoder<SellTokenInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['maxToken', getU64Decoder()],
  ]);
}

export function getSellTokenInstructionDataCodec(): Codec<
  SellTokenInstructionDataArgs,
  SellTokenInstructionData
> {
  return combineCodec(
    getSellTokenInstructionDataEncoder(),
    getSellTokenInstructionDataDecoder()
  );
}

export type SellTokenAsyncInput<
  TAccountSigner extends string = string,
  TAccountTokenAta extends string = string,
  TAccountSolEscrow extends string = string,
  TAccountTokenEscrow extends string = string,
  TAccountBondingCurve extends string = string,
  TAccountTokenMint extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  tokenAta: Address<TAccountTokenAta>;
  solEscrow?: Address<TAccountSolEscrow>;
  tokenEscrow: Address<TAccountTokenEscrow>;
  bondingCurve?: Address<TAccountBondingCurve>;
  tokenMint: Address<TAccountTokenMint>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  maxToken: SellTokenInstructionDataArgs['maxToken'];
};

export async function getSellTokenInstructionAsync<
  TAccountSigner extends string,
  TAccountTokenAta extends string,
  TAccountSolEscrow extends string,
  TAccountTokenEscrow extends string,
  TAccountBondingCurve extends string,
  TAccountTokenMint extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TProgramAddress extends Address = typeof PUMP_PROGRAM_ADDRESS,
>(
  input: SellTokenAsyncInput<
    TAccountSigner,
    TAccountTokenAta,
    TAccountSolEscrow,
    TAccountTokenEscrow,
    TAccountBondingCurve,
    TAccountTokenMint,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  SellTokenInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountTokenAta,
    TAccountSolEscrow,
    TAccountTokenEscrow,
    TAccountBondingCurve,
    TAccountTokenMint,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PUMP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    tokenAta: { value: input.tokenAta ?? null, isWritable: true },
    solEscrow: { value: input.solEscrow ?? null, isWritable: true },
    tokenEscrow: { value: input.tokenEscrow ?? null, isWritable: true },
    bondingCurve: { value: input.bondingCurve ?? null, isWritable: true },
    tokenMint: { value: input.tokenMint ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.bondingCurve.value) {
    accounts.bondingCurve.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([66, 79, 78, 68, 73, 78, 71, 95, 67, 85, 82, 86, 69])
        ),
        getAddressEncoder().encode(expectAddress(accounts.tokenMint.value)),
      ],
    });
  }
  if (!accounts.solEscrow.value) {
    accounts.solEscrow.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([66, 79, 78, 68, 73, 78, 71, 95, 67, 85, 82, 86, 69])
        ),
        getAddressEncoder().encode(expectAddress(accounts.tokenMint.value)),
        getAddressEncoder().encode(expectAddress(accounts.bondingCurve.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.tokenAta),
      getAccountMeta(accounts.solEscrow),
      getAccountMeta(accounts.tokenEscrow),
      getAccountMeta(accounts.bondingCurve),
      getAccountMeta(accounts.tokenMint),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
    ],
    programAddress,
    data: getSellTokenInstructionDataEncoder().encode(
      args as SellTokenInstructionDataArgs
    ),
  } as SellTokenInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountTokenAta,
    TAccountSolEscrow,
    TAccountTokenEscrow,
    TAccountBondingCurve,
    TAccountTokenMint,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >;

  return instruction;
}

export type SellTokenInput<
  TAccountSigner extends string = string,
  TAccountTokenAta extends string = string,
  TAccountSolEscrow extends string = string,
  TAccountTokenEscrow extends string = string,
  TAccountBondingCurve extends string = string,
  TAccountTokenMint extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  tokenAta: Address<TAccountTokenAta>;
  solEscrow: Address<TAccountSolEscrow>;
  tokenEscrow: Address<TAccountTokenEscrow>;
  bondingCurve: Address<TAccountBondingCurve>;
  tokenMint: Address<TAccountTokenMint>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  maxToken: SellTokenInstructionDataArgs['maxToken'];
};

export function getSellTokenInstruction<
  TAccountSigner extends string,
  TAccountTokenAta extends string,
  TAccountSolEscrow extends string,
  TAccountTokenEscrow extends string,
  TAccountBondingCurve extends string,
  TAccountTokenMint extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TProgramAddress extends Address = typeof PUMP_PROGRAM_ADDRESS,
>(
  input: SellTokenInput<
    TAccountSigner,
    TAccountTokenAta,
    TAccountSolEscrow,
    TAccountTokenEscrow,
    TAccountBondingCurve,
    TAccountTokenMint,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): SellTokenInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountTokenAta,
  TAccountSolEscrow,
  TAccountTokenEscrow,
  TAccountBondingCurve,
  TAccountTokenMint,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? PUMP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    tokenAta: { value: input.tokenAta ?? null, isWritable: true },
    solEscrow: { value: input.solEscrow ?? null, isWritable: true },
    tokenEscrow: { value: input.tokenEscrow ?? null, isWritable: true },
    bondingCurve: { value: input.bondingCurve ?? null, isWritable: true },
    tokenMint: { value: input.tokenMint ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.tokenAta),
      getAccountMeta(accounts.solEscrow),
      getAccountMeta(accounts.tokenEscrow),
      getAccountMeta(accounts.bondingCurve),
      getAccountMeta(accounts.tokenMint),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
    ],
    programAddress,
    data: getSellTokenInstructionDataEncoder().encode(
      args as SellTokenInstructionDataArgs
    ),
  } as SellTokenInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountTokenAta,
    TAccountSolEscrow,
    TAccountTokenEscrow,
    TAccountBondingCurve,
    TAccountTokenMint,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >;

  return instruction;
}

export type ParsedSellTokenInstruction<
  TProgram extends string = typeof PUMP_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    signer: TAccountMetas[0];
    tokenAta: TAccountMetas[1];
    solEscrow: TAccountMetas[2];
    tokenEscrow: TAccountMetas[3];
    bondingCurve: TAccountMetas[4];
    tokenMint: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
    tokenProgram: TAccountMetas[7];
    associatedTokenProgram: TAccountMetas[8];
  };
  data: SellTokenInstructionData;
};

export function parseSellTokenInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedSellTokenInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      tokenAta: getNextAccount(),
      solEscrow: getNextAccount(),
      tokenEscrow: getNextAccount(),
      bondingCurve: getNextAccount(),
      tokenMint: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
    },
    data: getSellTokenInstructionDataDecoder().decode(instruction.data),
  };
}
