/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  bytes,
  mapSerializer,
  publicKey as publicKeySerializer,
  struct,
  u64,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  expectPublicKey,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type BuyTokenInstructionAccounts = {
  signer: Signer;
  tokenAta?: PublicKey | Pda;
  tokenEscrow?: PublicKey | Pda;
  bondingCurve?: PublicKey | Pda;
  tokenMint: PublicKey | Pda;
  systemProgram?: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
  associatedTokenProgram?: PublicKey | Pda;
};

// Data.
export type BuyTokenInstructionData = {
  discriminator: Uint8Array;
  maxSol: bigint;
};

export type BuyTokenInstructionDataArgs = { maxSol: number | bigint };

export function getBuyTokenInstructionDataSerializer(): Serializer<
  BuyTokenInstructionDataArgs,
  BuyTokenInstructionData
> {
  return mapSerializer<
    BuyTokenInstructionDataArgs,
    any,
    BuyTokenInstructionData
  >(
    struct<BuyTokenInstructionData>(
      [
        ['discriminator', bytes({ size: 8 })],
        ['maxSol', u64()],
      ],
      { description: 'BuyTokenInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: new Uint8Array([138, 127, 14, 91, 38, 87, 115, 105]),
    })
  ) as Serializer<BuyTokenInstructionDataArgs, BuyTokenInstructionData>;
}

// Args.
export type BuyTokenInstructionArgs = BuyTokenInstructionDataArgs;

// Instruction.
export function buyToken(
  context: Pick<Context, 'eddsa' | 'programs'>,
  input: BuyTokenInstructionAccounts & BuyTokenInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'pump',
    'FPf834XQpnVNgFTKtihkik9Bc9c57859SdXAMNrQ554Q'
  );

  // Accounts.
  const resolvedAccounts = {
    signer: {
      index: 0,
      isWritable: true as boolean,
      value: input.signer ?? null,
    },
    tokenAta: {
      index: 1,
      isWritable: true as boolean,
      value: input.tokenAta ?? null,
    },
    tokenEscrow: {
      index: 2,
      isWritable: false as boolean,
      value: input.tokenEscrow ?? null,
    },
    bondingCurve: {
      index: 3,
      isWritable: false as boolean,
      value: input.bondingCurve ?? null,
    },
    tokenMint: {
      index: 4,
      isWritable: false as boolean,
      value: input.tokenMint ?? null,
    },
    systemProgram: {
      index: 5,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
    tokenProgram: {
      index: 6,
      isWritable: false as boolean,
      value: input.tokenProgram ?? null,
    },
    associatedTokenProgram: {
      index: 7,
      isWritable: false as boolean,
      value: input.associatedTokenProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: BuyTokenInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.tokenAta.value) {
    resolvedAccounts.tokenAta.value = context.eddsa.findPda(
      context.programs.getPublicKey(
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'
      ),
      [
        publicKeySerializer().serialize(
          expectPublicKey(resolvedAccounts.signer.value)
        ),
        bytes().serialize(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        publicKeySerializer().serialize(
          expectPublicKey(resolvedAccounts.tokenMint.value)
        ),
      ]
    );
  }
  if (!resolvedAccounts.bondingCurve.value) {
    resolvedAccounts.bondingCurve.value = context.eddsa.findPda(programId, [
      bytes().serialize(
        new Uint8Array([66, 79, 78, 68, 73, 78, 71, 95, 67, 85, 82, 86, 69])
      ),
      publicKeySerializer().serialize(
        expectPublicKey(resolvedAccounts.tokenMint.value)
      ),
    ]);
  }
  if (!resolvedAccounts.tokenEscrow.value) {
    resolvedAccounts.tokenEscrow.value = context.eddsa.findPda(
      context.programs.getPublicKey(
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'
      ),
      [
        publicKeySerializer().serialize(
          expectPublicKey(resolvedAccounts.bondingCurve.value)
        ),
        bytes().serialize(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        publicKeySerializer().serialize(
          expectPublicKey(resolvedAccounts.tokenMint.value)
        ),
      ]
    );
  }
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'systemProgram',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'tokenProgram',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }
  if (!resolvedAccounts.associatedTokenProgram.value) {
    resolvedAccounts.associatedTokenProgram.value =
      context.programs.getPublicKey(
        'associatedTokenProgram',
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'
      );
    resolvedAccounts.associatedTokenProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getBuyTokenInstructionDataSerializer().serialize(
    resolvedArgs as BuyTokenInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
