/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  bytes,
  mapSerializer,
  publicKey as publicKeySerializer,
  string,
  struct,
  u64,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  expectPublicKey,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type CreateTokenInstructionAccounts = {
  signer: Signer;
  globalState: PublicKey | Pda;
  bondingCurve?: PublicKey | Pda;
  mint: Signer;
  bondingCurveAta?: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
  systemProgram?: PublicKey | Pda;
  rent?: PublicKey | Pda;
  associatedTokenProgram?: PublicKey | Pda;
  tokenMetadataProgram?: PublicKey | Pda;
  metadata: PublicKey | Pda;
};

// Data.
export type CreateTokenInstructionData = {
  discriminator: Uint8Array;
  solReserve: bigint;
  tokenReserve: bigint;
  name: string;
  ticker: string;
  uri: string;
};

export type CreateTokenInstructionDataArgs = {
  solReserve: number | bigint;
  tokenReserve: number | bigint;
  name: string;
  ticker: string;
  uri: string;
};

export function getCreateTokenInstructionDataSerializer(): Serializer<
  CreateTokenInstructionDataArgs,
  CreateTokenInstructionData
> {
  return mapSerializer<
    CreateTokenInstructionDataArgs,
    any,
    CreateTokenInstructionData
  >(
    struct<CreateTokenInstructionData>(
      [
        ['discriminator', bytes({ size: 8 })],
        ['solReserve', u64()],
        ['tokenReserve', u64()],
        ['name', string()],
        ['ticker', string()],
        ['uri', string()],
      ],
      { description: 'CreateTokenInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: new Uint8Array([84, 52, 204, 228, 24, 140, 234, 75]),
    })
  ) as Serializer<CreateTokenInstructionDataArgs, CreateTokenInstructionData>;
}

// Args.
export type CreateTokenInstructionArgs = CreateTokenInstructionDataArgs;

// Instruction.
export function createToken(
  context: Pick<Context, 'eddsa' | 'programs'>,
  input: CreateTokenInstructionAccounts & CreateTokenInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'pump',
    'FPf834XQpnVNgFTKtihkik9Bc9c57859SdXAMNrQ554Q'
  );

  // Accounts.
  const resolvedAccounts = {
    signer: {
      index: 0,
      isWritable: true as boolean,
      value: input.signer ?? null,
    },
    globalState: {
      index: 1,
      isWritable: false as boolean,
      value: input.globalState ?? null,
    },
    bondingCurve: {
      index: 2,
      isWritable: true as boolean,
      value: input.bondingCurve ?? null,
    },
    mint: { index: 3, isWritable: true as boolean, value: input.mint ?? null },
    bondingCurveAta: {
      index: 4,
      isWritable: true as boolean,
      value: input.bondingCurveAta ?? null,
    },
    tokenProgram: {
      index: 5,
      isWritable: false as boolean,
      value: input.tokenProgram ?? null,
    },
    systemProgram: {
      index: 6,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
    rent: { index: 7, isWritable: false as boolean, value: input.rent ?? null },
    associatedTokenProgram: {
      index: 8,
      isWritable: false as boolean,
      value: input.associatedTokenProgram ?? null,
    },
    tokenMetadataProgram: {
      index: 9,
      isWritable: false as boolean,
      value: input.tokenMetadataProgram ?? null,
    },
    metadata: {
      index: 10,
      isWritable: true as boolean,
      value: input.metadata ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: CreateTokenInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.bondingCurve.value) {
    resolvedAccounts.bondingCurve.value = context.eddsa.findPda(programId, [
      bytes().serialize(
        new Uint8Array([66, 79, 78, 68, 73, 78, 71, 95, 83, 69, 69, 68])
      ),
      publicKeySerializer().serialize(
        expectPublicKey(resolvedAccounts.mint.value)
      ),
    ]);
  }
  if (!resolvedAccounts.bondingCurveAta.value) {
    resolvedAccounts.bondingCurveAta.value = context.eddsa.findPda(
      context.programs.getPublicKey(
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'
      ),
      [
        publicKeySerializer().serialize(
          expectPublicKey(resolvedAccounts.bondingCurve.value)
        ),
        bytes().serialize(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        publicKeySerializer().serialize(
          expectPublicKey(resolvedAccounts.mint.value)
        ),
      ]
    );
  }
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'tokenProgram',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'systemProgram',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }
  if (!resolvedAccounts.rent.value) {
    resolvedAccounts.rent.value = context.programs.getPublicKey(
      'rent',
      'SysvarRent111111111111111111111111111111111'
    );
    resolvedAccounts.rent.isWritable = false;
  }
  if (!resolvedAccounts.associatedTokenProgram.value) {
    resolvedAccounts.associatedTokenProgram.value =
      context.programs.getPublicKey(
        'associatedTokenProgram',
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'
      );
    resolvedAccounts.associatedTokenProgram.isWritable = false;
  }
  if (!resolvedAccounts.tokenMetadataProgram.value) {
    resolvedAccounts.tokenMetadataProgram.value = context.programs.getPublicKey(
      'tokenMetadataProgram',
      'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s'
    );
    resolvedAccounts.tokenMetadataProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getCreateTokenInstructionDataSerializer().serialize(
    resolvedArgs as CreateTokenInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
