/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  bytes,
  mapSerializer,
  struct,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type InitGlobalConfigInstructionAccounts = {
  globalConfig?: PublicKey | Pda;
  signer?: Signer;
  systemProgram?: PublicKey | Pda;
};

// Data.
export type InitGlobalConfigInstructionData = { discriminator: Uint8Array };

export type InitGlobalConfigInstructionDataArgs = {};

export function getInitGlobalConfigInstructionDataSerializer(): Serializer<
  InitGlobalConfigInstructionDataArgs,
  InitGlobalConfigInstructionData
> {
  return mapSerializer<
    InitGlobalConfigInstructionDataArgs,
    any,
    InitGlobalConfigInstructionData
  >(
    struct<InitGlobalConfigInstructionData>(
      [['discriminator', bytes({ size: 8 })]],
      { description: 'InitGlobalConfigInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: new Uint8Array([140, 136, 214, 48, 87, 0, 120, 255]),
    })
  ) as Serializer<
    InitGlobalConfigInstructionDataArgs,
    InitGlobalConfigInstructionData
  >;
}

// Instruction.
export function initGlobalConfig(
  context: Pick<Context, 'eddsa' | 'programs'>,
  input: InitGlobalConfigInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'pump',
    'FPf834XQpnVNgFTKtihkik9Bc9c57859SdXAMNrQ554Q'
  );

  // Accounts.
  const resolvedAccounts = {
    globalConfig: {
      index: 0,
      isWritable: true as boolean,
      value: input.globalConfig ?? null,
    },
    signer: {
      index: 1,
      isWritable: true as boolean,
      value: input.signer ?? null,
    },
    systemProgram: {
      index: 2,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Default values.
  if (!resolvedAccounts.globalConfig.value) {
    resolvedAccounts.globalConfig.value = context.eddsa.findPda(programId, [
      bytes().serialize(
        new Uint8Array([
          103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
        ])
      ),
    ]);
  }
  if (!resolvedAccounts.signer.value) {
    resolvedAccounts.signer.value = context.programs.getPublicKey(
      'signer',
      '52nvBaMXujpVYf6zBUvmQtHEZc4kAncRJccXG99F6yrg'
    );
    resolvedAccounts.signer.isWritable = false;
  }
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'systemProgram',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getInitGlobalConfigInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
