/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  bytes,
  mapSerializer,
  publicKey as publicKeySerializer,
  struct,
  u64,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  expectPublicKey,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type SellTokenInstructionAccounts = {
  signer: Signer;
  tokenAta: PublicKey | Pda;
  solEscrow?: PublicKey | Pda;
  tokenEscrow: PublicKey | Pda;
  bondingCurve?: PublicKey | Pda;
  tokenMint: PublicKey | Pda;
  systemProgram?: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
  associatedTokenProgram?: PublicKey | Pda;
};

// Data.
export type SellTokenInstructionData = {
  discriminator: Uint8Array;
  maxToken: bigint;
};

export type SellTokenInstructionDataArgs = { maxToken: number | bigint };

export function getSellTokenInstructionDataSerializer(): Serializer<
  SellTokenInstructionDataArgs,
  SellTokenInstructionData
> {
  return mapSerializer<
    SellTokenInstructionDataArgs,
    any,
    SellTokenInstructionData
  >(
    struct<SellTokenInstructionData>(
      [
        ['discriminator', bytes({ size: 8 })],
        ['maxToken', u64()],
      ],
      { description: 'SellTokenInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: new Uint8Array([109, 61, 40, 187, 230, 176, 135, 174]),
    })
  ) as Serializer<SellTokenInstructionDataArgs, SellTokenInstructionData>;
}

// Args.
export type SellTokenInstructionArgs = SellTokenInstructionDataArgs;

// Instruction.
export function sellToken(
  context: Pick<Context, 'eddsa' | 'programs'>,
  input: SellTokenInstructionAccounts & SellTokenInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'pump',
    'FPf834XQpnVNgFTKtihkik9Bc9c57859SdXAMNrQ554Q'
  );

  // Accounts.
  const resolvedAccounts = {
    signer: {
      index: 0,
      isWritable: true as boolean,
      value: input.signer ?? null,
    },
    tokenAta: {
      index: 1,
      isWritable: true as boolean,
      value: input.tokenAta ?? null,
    },
    solEscrow: {
      index: 2,
      isWritable: true as boolean,
      value: input.solEscrow ?? null,
    },
    tokenEscrow: {
      index: 3,
      isWritable: true as boolean,
      value: input.tokenEscrow ?? null,
    },
    bondingCurve: {
      index: 4,
      isWritable: true as boolean,
      value: input.bondingCurve ?? null,
    },
    tokenMint: {
      index: 5,
      isWritable: false as boolean,
      value: input.tokenMint ?? null,
    },
    systemProgram: {
      index: 6,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
    tokenProgram: {
      index: 7,
      isWritable: false as boolean,
      value: input.tokenProgram ?? null,
    },
    associatedTokenProgram: {
      index: 8,
      isWritable: false as boolean,
      value: input.associatedTokenProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: SellTokenInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.bondingCurve.value) {
    resolvedAccounts.bondingCurve.value = context.eddsa.findPda(programId, [
      bytes().serialize(
        new Uint8Array([66, 79, 78, 68, 73, 78, 71, 95, 67, 85, 82, 86, 69])
      ),
      publicKeySerializer().serialize(
        expectPublicKey(resolvedAccounts.tokenMint.value)
      ),
    ]);
  }
  if (!resolvedAccounts.solEscrow.value) {
    resolvedAccounts.solEscrow.value = context.eddsa.findPda(programId, [
      bytes().serialize(
        new Uint8Array([66, 79, 78, 68, 73, 78, 71, 95, 67, 85, 82, 86, 69])
      ),
      publicKeySerializer().serialize(
        expectPublicKey(resolvedAccounts.tokenMint.value)
      ),
      publicKeySerializer().serialize(
        expectPublicKey(resolvedAccounts.bondingCurve.value)
      ),
    ]);
  }
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'systemProgram',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      'tokenProgram',
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }
  if (!resolvedAccounts.associatedTokenProgram.value) {
    resolvedAccounts.associatedTokenProgram.value =
      context.programs.getPublicKey(
        'associatedTokenProgram',
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'
      );
    resolvedAccounts.associatedTokenProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getSellTokenInstructionDataSerializer().serialize(
    resolvedArgs as SellTokenInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
