/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  ClusterFilter,
  Context,
  Program,
  PublicKey,
} from '@metaplex-foundation/umi';
import { getPumpErrorFromCode, getPumpErrorFromName } from '../errors';

export const PUMP_PROGRAM_ID =
  'FPf834XQpnVNgFTKtihkik9Bc9c57859SdXAMNrQ554Q' as PublicKey<'FPf834XQpnVNgFTKtihkik9Bc9c57859SdXAMNrQ554Q'>;

export function createPumpProgram(): Program {
  return {
    name: 'pump',
    publicKey: PUMP_PROGRAM_ID,
    getErrorFromCode(code: number, cause?: Error) {
      return getPumpErrorFromCode(code, this, cause);
    },
    getErrorFromName(name: string, cause?: Error) {
      return getPumpErrorFromName(name, this, cause);
    },
    isOnCluster() {
      return true;
    },
  };
}

export function getPumpProgram<T extends Program = Program>(
  context: Pick<Context, 'programs'>,
  clusterFilter?: ClusterFilter
): T {
  return context.programs.get<T>('pump', clusterFilter);
}

export function getPumpProgramId(
  context: Pick<Context, 'programs'>,
  clusterFilter?: ClusterFilter
): PublicKey {
  return context.programs.getPublicKey('pump', PUMP_PROGRAM_ID, clusterFilter);
}
